site_name: Python Support Scripts
site_description: macOS and Windows installer docs
site_dir: ../site
docs_dir: .

nav:
  - Home: index.md
  - macOS:
      - Installation scripts:
          - Components: macos/components.md
          - Orchestration and GUI: macos/orchestration.md
  - Windows:
      - Installation scripts:
          - Components: windows/index.md
  - GitHub CI: ci.md

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: true
  - tables