name: Quarto Render Check

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'quarto-onboarding/**'
      - '.github/workflows/quarto-check.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  quarto-render:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: quarto-onboarding