name: Quarto Render Check

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'quarto-onboarding/**'
      - '.github/workflows/quarto-check.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  quarto-render:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Quarto Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: quarto-onboarding